/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package medianotes;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MedianotesApplication {

    public static void main(String[] args) {
        SpringApplication.run(MedianotesApplication.class);
    }
}
